#ifndef STATUS_H
#define STATUS_H

typedef enum
{
    STATUS_SUCCESS,
    STATUS_INPUT_ERROR,
    STATUS_SENTENCE_LENGTH_ERROR,
    STATUS_WORD_LENGTH_ERROR,
    STATUS_MONTH_ERROR,
    STATUS_DAY_ERROR,
    STATUS_YEAR_ERROR,
} return_code_t;

#endif
